[package]
name = "DarbitexTokenVault"
version = "0.1.0"
upgrade_policy = "immutable"
authors = ["Rera", "Claude (Anthropic)"]
license = "Unlicense"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[addresses]
darbitex_vault = "_"

[dev-addresses]
darbitex_vault = "0xBEEF"
